on:
  pull_request:
    types: [closed]

jobs:
  autoclose:
    permissions:
      pull-requests: read
      issues: write
    runs-on: ubuntu-latest
    steps:
    - name: Close linked issues
      if: github.event.pull_request.merged == true
      run: |
        for issue in `gh pr view "$NUMBER" --json closingIssuesReferences --jq '.closingIssuesReferences[].number'`; do
          gh issue close $issue --reason completed --comment "Auto-closed by merging PR #$NUMBER: $TITLE";
        done
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GH_REPO: ${{ github.repository }}
        NUMBER: ${{ github.event.pull_request.number}}
        TITLE: ${{ github.event.pull_request.title }}
