name: Publish Extension

permissions:
  contents: write

on:
  workflow_dispatch:
    inputs:
      version:
        type: choice
        description: 'Bump version'
        required: true
        default: 'patch'
        options:
          - 'major'
          - 'minor'
          - 'patch'
          - 'none'

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 'latest'

    - name: Build
      run: |
        npm install
        npm run compile
      
    - name: Bump version, commit and tag
      run: |
        git config --global user.name "Github Actions"
        git config --global user.email "actions@github.com"
        npm version ${{ github.event.inputs.version }} -m "Bump version to %s"
        git push --tags https://Pasu4:${{secrets.GITHUB_TOKEN}}:@github.com/Pasu4/neuropilot
    
    - name: Publish extension
      run: npx @vscode/vsce publish -p ${{secrets.MARKETPLACE_TOKEN}} --allow-star-activation
